<?php

namespace ProgrammatorDev\OpenWeatherMap\Test\Response;

class MockResponse
{
    public const GEOCODING_DIRECT = '[{"name":"Lisbon","local_names":{"he":"ליסבון","rm":"Lisbona","sw":"Lisbon","gv":"Lisboa","sr":"Лисабон","eo":"Lisbono","fo":"Lisboa","fi":"Lissabon","te":"లిస్బన్","de":"Lissabon","sc":"Lisbona","uk":"Лісабон","kn":"ಲಿಸ್ಬೊನ್","lv":"Lisabona","an":"Lisbona","ar":"لشبونة","cs":"Lisabon","ms":"Lisbon","sh":"Lisabon","jv":"Lisabon","ty":"Lisboa","sq":"Lisbona","la":"Olisipo","ru":"Лиссабон","gn":"Lisimbã","qu":"Lisboa","ba":"Лиссабон","tr":"Lizbon","ascii":"Lisbon","st":"Lisbon","bs":"Lisabon","my":"လစ်စဘွန်းမြို့","am":"ሊዝቦን","tw":"Lisbon","fr":"Lisbonne","fa":"لیسبون","sv":"Lissabon","ro":"Lisabona","hy":"Լիսաբոն","sa":"लिस्बन","ia":"Lisbona","vi":"Lisboa","it":"Lisbona","feature_name":"Lisbon","hi":"लिस्बन","gd":"Lisbon","kv":"Лиссабон","da":"Lissabon","os":"Лиссабон","yo":"Lisbon","ta":"லிஸ்பன்","br":"Lisbon","nl":"Lissabon","hu":"Lisszabon","ga":"Liospóin","cv":"Лиссабон","pl":"Lizbona","ie":"Lisboa","nn":"Lisboa","rn":"Lisboa","mk":"Лисабон","be":"Лісабон","ca":"Lisboa","en":"Lisbon","no":"Lisboa","yi":"ליסבאן","kw":"Lisboa","eu":"Lisboa","ja":"リスボン","sl":"Lizbona","bg":"Лисабон","id":"Lisboa","ka":"ლისაბონი","zh":"里斯本","kk":"Лиссабон","is":"Lissabon","sk":"Lisabon","tg":"Лиссабон","lt":"Lisabona","mr":"लिस्बन","cy":"Lisbon","ky":"Лиссабон","gl":"Lisboa","et":"Lissabon","ee":"Lisbon","ko":"리스본","bn":"লিসবন","bo":"ལི་སི་བཱོན།","es":"Lisboa","ug":"لىسبون","vo":"Lisboa","fy":"Lissabon","ln":"Lisboa","ku":"Lîzbon","el":"Λισαβόνα","wo":"Lisbon","ml":"ലിസ്‌ബൺ","tl":"Lisboa","pt":"Lisboa","ur":"لزبن","ht":"Lisbòn","oc":"Lisbona","co":"Lisbona","hr":"Lisabon","th":"ลิสบอน","io":"Lisboa","tt":"Лиссабон","mi":"Rihipone"},"lat":38.7077507,"lon":-9.1365919,"country":"PT"}]';
    public const GEOCODING_REVERSE = self::GEOCODING_DIRECT;
    public const GEOCODING_ZIP = '{"zip":"1000-001","name":"Lisbon","lat":38.7167,"lon":-9.1333,"country":"PT"}';
}